import apiClient from './apiClient';

export const getTodoList = () =>
  apiClient.get<TodoTypeParam>(
    'https://killsanghyuck.github.io/prography_5th_front/todoDummy.json',
  );
// export interface TodoTypeParams<> {
//   id: string;
//   title: string;
//   status: string;
// }
// Generated by https://quicktype.io

export interface TodoTypeParam {
  statusCode: number;
  body: Body[];
}

export interface Body {
  id: number;
  status: string;
  title: string;
}
